### ISSUE TITLE
解析消息ID报错问题

### ISSUE THREAD

**Issue by toby2o12** [tangxuehua/equeue#31]
消息ID例子:"0a0acbb5881300007090330000000000"
**报错原因**

IPAddress初始化时接受参数如果是负数,报错信息为**Specified argument was out of the range of valid values. Parameter name: newAddress**
解决办法
var ip = BitConverter.ToInt32(ipBytes, 0);
改为
var ip = BitConverter.ToUInt32(ipBytes, 0);

public static MessageIdInfo ParseMessageId(string messageId)
        {
            var messageIdBytes = ObjectId.ParseHexString(messageId);
            var ipBytes = new byte[4];
            var portBytes = new byte[4];
            var messagePositionBytes = new byte[8];

            Buffer.BlockCopy(messageIdBytes, 0, ipBytes, 0, 4);
            Buffer.BlockCopy(messageIdBytes, 4, portBytes, 0, 4);
            Buffer.BlockCopy(messageIdBytes, 8, messagePositionBytes, 0, 8);

            var ip = BitConverter.ToInt32(ipBytes, 0);
            var port = BitConverter.ToInt32(portBytes, 0);
            var messagePosition = BitConverter.ToInt64(messagePositionBytes, 0);

            return new MessageIdInfo
            {
                IP = new IPAddress(ip),
                Port = port,
                MessagePosition = messagePosition
            };
        }

**Comment by tangxuehua** [comment]
IPAddress初始化时为何会接收负数？能说明一下原因吗

**Comment by tangxuehua** [comment]
fixed
